NumPy (Numerical Python)

In [5]:
import numpy

In [6]:
numpy.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [7]:
numpy.array([11,12,13,14,15,16,17])

array([11, 12, 13, 14, 15, 16, 17])

In [8]:
numpy.array([100,200,300,400,500,600,700])

array([100, 200, 300, 400, 500, 600, 700])

In [9]:
import numpy as np

In [10]:
np.array([10,20,30,40])

array([10, 20, 30, 40])

In [11]:
a=np.array([12,14,16,18,20,22])

In [12]:
a

array([12, 14, 16, 18, 20, 22])

In [13]:
a.ndim

1

In [13]:
a.size

6

In [14]:
a.shape

(6,)

In [16]:
b=np.array([10,20,30,40,50,60,70,80])

In [17]:
b

array([10, 20, 30, 40, 50, 60, 70, 80])

In [18]:
b.size

8

In [19]:
c=np.array([44,55,66,77,88])

In [17]:
c

array([44, 55, 66, 77, 88])

In [20]:
c.dtype

dtype('int32')

In [18]:
c.size

5

In [21]:
d=np.array([34.5,22.1,67.8,98.4,25.6])

In [20]:
d

array([34.5, 22.1, 67.8, 98.4, 25.6])

In [22]:
d.dtype

dtype('float64')

In [22]:
d.size

5

In [23]:
e=np.array([12,14,15,16,17],dtype='int')

In [24]:
e

array([12, 14, 15, 16, 17])

In [25]:
e.dtype

dtype('int32')

In [24]:
e=np.array([12,14,15,16,17],dtype='float')

In [27]:
e

array([12., 14., 15., 16., 17.])

In [28]:
e.dtype

dtype('float64')

In [25]:
e.size

5

In [30]:
#f=np.array([[c1,c2],[c1,c2]])

In [26]:
f=np.array([[1,2],[3,4]])

In [28]:
f

array([[1, 2],
       [3, 4]])

In [33]:
f.size

4

In [27]:
f.shape

(2, 2)

In [30]:
g=np.array([[13,14],[15,16]])

In [31]:
g

array([[13, 14],
       [15, 16]])

In [32]:
g.size    #no of elements

4

In [38]:
g.shape

(2, 2)

In [39]:
g.dtype

dtype('int32')

In [35]:
g.itemsize   #no of bytes

4

In [33]:
h=np.array([[10,20],[30,40],[50,60]])

In [41]:
h

array([[10, 20],
       [30, 40],
       [50, 60]])

In [34]:
h.size   #no of elements

6

In [71]:
h.min()

10

In [72]:
h.max()

60

In [63]:
h.shape

(3, 2)

In [64]:
h.dtype

dtype('int32')

In [36]:
h.itemsize #4byte

4

In [68]:
h.ndim  #no of dimensions

2

In [37]:
#2rows 3columns
i=np.array([[4,5,6],[7,8,9]])

In [47]:
i

array([[4, 5, 6],
       [7, 8, 9]])

In [48]:
i.size

6

In [49]:
i.shape

(2, 3)

In [50]:
i.dtype

dtype('int32')

In [38]:
i=np.array([[4,5,6],[7,8,9]],dtype='float')

In [52]:
i

array([[4., 5., 6.],
       [7., 8., 9.]])

In [53]:
i.dtype

dtype('float64')

In [70]:
i.ndim

2

shapes rows & columns
(4,2)(4,3)(3,4)(3,3)(4,5)(5,5)(2,5)(5,3)

In [73]:
i.min()

4.0

In [74]:
i.max()

9.0

In [75]:
h

array([[10, 20],
       [30, 40],
       [50, 60]])

In [76]:
h.shape

(3, 2)

In [39]:
h.reshape(2,3)

array([[10, 20, 30],
       [40, 50, 60]])

In [40]:
j=np.arange(15)

In [79]:
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [80]:
j.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [81]:
j.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [41]:
k=np.arange(25)

In [83]:
k

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [42]:
p=k.reshape(5,5)

In [87]:
p

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [43]:
x=np.zeros([3,3])

In [92]:
x

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [44]:
y=np.ones([3,3])

In [94]:
y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [95]:
x+y

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

Broadcasting in Numpy

In [45]:
a=np.array([2,3,4,5])
a

array([2, 3, 4, 5])

In [47]:
b=np.array([10,20,30,40])
b

array([10, 20, 30, 40])

In [48]:
a*b

array([ 20,  60, 120, 200])

In [100]:
a+b

array([12, 23, 34, 45])

In [101]:
a-b

array([ -8, -17, -26, -35])

In [49]:
c=np.array([10,20,30,40,50])
c

array([10, 20, 30, 40, 50])

In [103]:
c*2

array([ 20,  40,  60,  80, 100])

In [104]:
c**2

array([ 100,  400,  900, 1600, 2500])

In [50]:
p=np.random.random([3,3])

In [106]:
p

array([[0.14577924, 0.82085788, 0.12448394],
       [0.50104843, 0.4160631 , 0.92267575],
       [0.00892653, 0.0948763 , 0.52232209]])

In [51]:
q=np.ones([3,3])

In [110]:
q

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
p+q

array([[1.50994124, 1.87214046, 1.59077054],
       [1.56972056, 1.81432153, 1.75302575],
       [1.19264544, 1.94216467, 1.59134312]])

Universal Fuctions:

In [53]:
b=np.arange(3)

In [55]:
b

array([0, 1, 2])

In [56]:
np.exp(b)

array([1.        , 2.71828183, 7.3890561 ])

In [57]:
np.sqrt(b)

array([0.        , 1.        , 1.41421356])

In [58]:
c=np.array([2,1,4])
np.add(b,c)

array([2, 2, 6])

Indexing, Slicing and Iterating

In [5]:
import numpy as np

In [6]:
a=np.arange(10)

In [7]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
a[2]     #indexng

2

In [10]:
a[2:5]

array([2, 3, 4])

In [54]:
j

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [113]:
j[4]

4

In [114]:
j[9]

9

In [115]:
j[5:8]

array([5, 6, 7])

In [116]:
j[8:12]

array([ 8,  9, 10, 11])

In [117]:
j[-1]

14

In [119]:
j[-2]

13

In [2]:
import numpy as np

In [3]:
a=np.array([24,45,np.nan,90,60,34,np.nan,22,21])

In [4]:
a

array([24., 45., nan, 90., 60., 34., nan, 22., 21.])